#!/bin/sh

case "${1}" in
   start)
      echo -n "Starting openhab_monitor.sh..."
      /bin/openhab_monitor.sh > /var/log/openhab_monitor.log 2>&1 &
      echo
      ;;

   stop)
      echo -n "Stopping openhab_monitor.sh..."
      killall openhab_monitor.sh
      echo
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: $0 [start|stop|restart]"
      ;;
esac
