#!/bin/sh

case "${1}" in
   start)
      echo -n "Starting openhab_monitor.php..."
      /usr/bin/php /bin/openhab_monitor.php > /var/log/openhab_monitor.log 2>&1 &
      echo
      ;;

   stop)
      echo -n "Stopping openhab_monitor.php..."
      kill -9 `ps -eo pid,args | grep '/bin/[o]penhab_monitor.php' | awk '{ print $1 }'`
      echo
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: $0 [start|stop|restart]"
      ;;
esac
